### ISSUE TITLE
File Drops not working

### ISSUE THREAD

**Issue by MRVDOG** [OckePocke/ng2-files-drop#1]
Hey, I set my app up to include ng2-files-drop like the readme.md says, it seems the module isn't being initialised...

app.module.ts
![2702WJdCqT](https://ss.mrvdog.com/2702WJdCqT.raw)

home.component.ts
![272xqXkYOY](https://ss.mrvdog.com/272xqXkYOY.raw)

home.component.html
![2711XcNQZh](https://ss.mrvdog.com/2711XcNQZh.raw)

I'm trying to grab file names from .jar files, but when I drop a file on the element, chrome initiates a download, and I don't get an event logged in the console
![273MwonasI](https://ss.mrvdog.com/273MwonasI.raw)
![2741Mdz5WQ](https://ss.mrvdog.com/2741Mdz5WQ.raw)

any ideas as to what I'm doing wrong?

**Comment by OckePocke** [comment]
It seems to be the `<md-list>` that doesn't work together with opFilesDrop. I wrapped the `<md-list>` inside a `<div>` and then it worked fine.

```
<div opFilesDrop (opFilesDropDropped)="dragFilesDropped($event)"
          (opFilesDropOver)="dragFilesOver($event)">
  <md-list>
    <md-list-item>Item 1</md-list-item>
    <md-list-item>Item 2</md-list-item>
  </md-list>
</div>
```
